GET http://localhost:4000/test

###
POST http://localhost:4000/user-api/register
Content-Type: application/json

{
 "name": "Chaitanya", 
 "email" : "Chaitanya@gmail.com",
 "password" : "Chaitany@Wal"
}