GET http://localhost:4000/test

###
POST http://localhost:4000/user-api/register
Content-Type: application/json

{
 "name": "Chaitanya", 
 "email" : "Chaitanya@gmail.com",
 "password" : "Chaitu@123"
}


###
GET http://localhost:4000/user-api/user/Chaitanya
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2VraGFyIiwiaWF0IjoxNjc4MTg4MjA0LCJleHAiOjE2NzgxOTE4MDR9.Ept6FK1vOO8SkpbzNeN0Za49Z_L-DF8GOXnx0ORKJAM


###
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
 "name": "sekhar", 
 "email" : "sekhar@gmail.com",
 "password" : "sekha23"
}


###
put http://localhost:4000/user-api/modify-user/sekhar
Content-Type: application/json

{
  "name": "sekhar", 
 "email" : "sekhar@gmail.com",
 "password" : "sekha23"

}


###
DELETE http://localhost:4000/user-api/delete-user/Chaitanya
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2VraGFyIiwiaWF0IjoxNjc4MTg4MjA0LCJleHAiOjE2NzgxOTE4MDR9.Ept6FK1vOO8SkpbzNeN0Za49Z_L-DF8GOXnx0ORKJAM

